import Head from "next/head"
import { Rubik } from "@next/font/google"

import { SubmitHandler, useForm } from "react-hook-form"

const rubik = Rubik({ subsets: ["latin"] })

export default function Home() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>()

  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    console.log(data)
  }

  return (
    <>
      <Head>
        <title>Caesar Cipher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={rubik.className}>
        <div className="container">
          <div className=" flex flex-row justify-center items-center h-screen ">
            <h1>Caesar Cipher</h1>

            <form
              className="flex flex-col bg-yellow-600 w-screen "
              onSubmit={handleSubmit(onSubmit)}
            >
              <label htmlFor="str">Secret </label>
              <input
                {...register("str", { required: true })}
                type="text"
                className="p-3 border-4
         border-indigo-500 text-indigo-900 rounded-3xl active:bg-slate-200 focus:bg-slate-200 outline-none"
              />

              {errors.str && <span className=" text-red-600 text-xs ">This field is required</span>}
              <label htmlFor="cipher">Cipher</label>
              <input {...register("cipher", { required: true })} type="text" className="" />
              {errors.cipher && <span className=" text-red-600 text-xs">Cipher is required!</span>}
              <button className="p-2 border-4 rounded-xl mt-6 border-black hover:shadow-2xl hover:bg-slate-200 outline-none focus:border-green-300">
                Code it!
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  )
}

type Inputs = {
  str: string
  cipher: string
}
