import Head from "next/head"
import { useState } from "react"
import { Rubik } from "@next/font/google"
import Result from "../components/Result"
import Form from "../components/Form"
import RenderThemeChanger from "../customHooks/renderThemeChanger"
import { ToastContainer } from "react-toastify"
const rubik = Rubik({ subsets: ["latin"] })
import { useTheme } from "next-themes"

export default function Home() {
  const [code, setCode] = useState("")
  const { theme } = useTheme()
  const themeMode = theme === "dark" ? "dark" : "light"

  return (
    <>
      <Head>
        <title>Caesar Cipher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={rubik.className}>
        <div className="container flex h-screen flex-col items-center justify-center">
          <h1 className="mb-8 text-3xl uppercase">Caesar Cipher</h1>
          {code && <Result code={code} setCode={setCode} />}
          <Form setCode={setCode} />
          <div className=" mt-8 cursor-pointer transition-all hover:scale-125">
            {RenderThemeChanger && RenderThemeChanger()}
          </div>
        </div>
        <ToastContainer
          position="bottom-center"
          autoClose={2000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
          theme={themeMode}
        />
      </main>
    </>
  )
}
